version: '3'
services:
  jobs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ~/.ssh:/root/.ssh

  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    command: soketi start
    environment:
      SOKETI_DEBUG: '1'
      SOKETI_METRICS_SERVER_PORT: '9601'
      SOKETI_DEFAULT_APP_ID: 'app-id'
      SOKETI_DEFAULT_APP_KEY: 'app-key'
      SOKETI_DEFAULT_APP_SECRET: 'app-secret'
      PUSHER_HOST: '127.0.0.1'
      PUSHER_PORT: '6001'
      PUSHER_SCHEME: 'http'
      METRICS_SERVER_PORT: '9601'
    ports:
      - "6001:6001"
      - '9601:9601'
    networks:
      - soketi_network
    volumes:
      - .:/var/www

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan serve --port=8090
    ports:
      - "8090:8090"
    network_mode: 'host'
    volumes:
      - .:/var/www
    depends_on:
      - jobs
      - websocket

networks:
  soketi_network:
    driver: bridge